
version: 2.1

orbs:
  python: circleci/python@1.2


jobs:
  build-and-test:

    docker:
      - image: cimg/python:3.8
      
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"


workflows:
  sample:
    jobs:
      - build-and-test
