version: 2
jobs:
  build:
    circleci_ip_ranges: true
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 tests.py
      #- store_artifacts:
          #path: test-reports/
          #destination: python_app
      - run:
          name: list python file
          command: ls
      - run:
          name: ip
          command: ifconfig
      - run:
          name: scp
          command: scp -P 12312 tests.py ubuntu@13.209.100.150:/scloud/test
