version: 2.1

#########
# Common
#########
orbs:
  python: circleci/python@1.4.0

#################
# Job Definitions
##################
jobs:
  build:
  
    docker:
      - image: cimg/python:3.10.0
      
    steps:
      - checkout
      - run:
          name: Deploy
          command: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install -b ~/bin/aws

            PUBLIC_IP=$(curl ipinfo.io/ip)
 
            AWS_REGION=ap-northeast-2
  
            SG_ID=sg-0a3a1d6cbfb75935c

            ~/bin/aws/aws ec2 authorize-security-group-ingress --region $AWS_REGION --group-id $SG_ID \
              --protocol tcp --port 22 --cidr $PUBLIC_IP/24

            sleep 5

            EC2_USERNAME=ubuntu
   
            EC2_PUBLIC_DNS=ec2-52-79-123-136.ap-northeast-2.compute.amazonaws.com
            ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_PUBLIC_DNS \

            ~/bin/aws/aws ec2 revoke-security-group-ingress --region $AWS_REGION --group-id $SG_ID \
              --protocol tcp --port 22 --cidr $PUBLIC_IP/24

############
# Workflows
############
workflows:
  sample: 
    jobs:
      - build
