version: 2.1

#########
# Common
#########
orbs:
  python: circleci/python@1.4.0

##################
# Job Definitions
##################
jobs:
  build:
    docker:
      - image: cimg/python:3.10.0
    steps:
      - checkout
      - run: python --version

############
# Workflows
############
workflows:
  sample: 
    jobs:
      - build
