version: 2.1

#########
# Common
#########
orbs:
  python: circleci/python@1.4.0

#################
# Job Definitions
##################
jobs:
  build:
  
    docker:
      - image: cimg/python:3.10.0
      
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a8:14:a7:83:15:d9:c1:d3:2f:15:95:26:af:ec:1a:e4"
      - run:
          name: Deploy Over SSH
          command: ssh ubuntu@52.79.123.136

############
# Workflows
############
workflows:
  sample: 
    jobs:
      - build
