version: 2.1

#########
# Common
#########
orbs:
  python: circleci/python@1.4.0
  aws-sg-white-list-circleci-ip: inokappa/aws-sg-white-list-circleci-ip@0.0.3

##################
# Job Definitions
##################
jobs:
  build:
  
    docker:
      - image: cimg/python:3.10.0
      
    steps:
      - run: pwd
      - run: ls
      - run:
          name: Deploy Over SSH
          command: scp -r -o StrictHostKeyChecking=no ./ ubuntu@52.79.123.136:/home/ubuntu
         

############
# Workflows
############
workflows:
  sample: 
    jobs:
      - build
